
services:
 express-app: # Сервер Express
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads  # ← КЛЮЧЕВОЕ: сохраняем загруженные файлы
      - ./prisma:/app/prisma    # опционально: для схемы Prisma
 react-app: # React-приложение
    build: ../react-client # Путь к вашему React-приложению относительно корня вашего проекта
    ports:
       - '80:80' # Порт, на котором будет доступно ваше React-приложение
       - '8000:8000' # Порт, на котором будет доступно ваше React-приложение



